### ISSUE TITLE
When update is called, the list is doubled

### ISSUE THREAD

**Issue by aksineDby** [afonja14755/ux-select#2]
In function `private createGroupAndOptions() {` I found some problem: Without the `isSearchable` option, the updated list has a double display. I think problem is here:
```
    if (this.uxBody.childNodes[1]) {
      this.uxBody.replaceChild(selectList, this.uxBody.childNodes[1]);
    } else {
      this.uxBody.appendChild(selectList);
    }
```
Not sure of the correctness, but here's my example of how to solve the problem
```
const indexList = this.config.isSearchable ? 1 : 0;

if (this.uxBody.childNodes[indexList]) {
  this.uxBody.replaceChild(selectList, this.uxBody.childNodes[indexList]);
} else {
  this.uxBody.appendChild(selectList);
}

**Comment by afonja14755** [comment]
Thank you for your request. The bug has been fixed in the latest release.
