### ISSUE TITLE
Non ES-module UxSelect not defined

### ISSUE THREAD

**Issue by William-H-M** [afonja14755/ux-select#5]
Hi, when using the non ES-modulo and initiating the instance as per the README

`const myUxSelect = new UxSelect(element, params);`

Throws an error because on the iife file is called as `this["ux-select"]` a better option would be to be called `UxSelect`, this can be fixed on the vite.config setting `lib:name` to "UxSelect" or to whatever you see more appropriate

**Comment by afonja14755** [comment]
Thank you for your inquiry. The bug will be fixed in the latest version.

**Comment by afonja14755** [comment]
Fixed in [2.5.0](https://github.com/afonja14755/ux-select/releases/tag/v2.5.0) release
