### ISSUE TITLE
[Feature-Request] Remove diacritics from search

### ISSUE THREAD

**Issue by William-H-M** [afonja14755/ux-select#6]
Hi, when using the search function and if some of the options does have a diacritic then it wouldn't be able to find it, one way to do it is on the search function to remove them from the searched text and the original one.

On 
https://github.com/afonja14755/ux-select/blob/386732ac97cae87c1af7b008d3355aa1b0dd33d8/src/ux-select.ts#L551
Replace for something like
```
const text = input.value
  .toLowerCase()
  .normalize('NFD')
  .replace(/\p{Diacritic}/gu, '');
```
And on
https://github.com/afonja14755/ux-select/blob/386732ac97cae87c1af7b008d3355aa1b0dd33d8/src/ux-select.ts#L572
Replace for
```
const match = searchValue.test(
  option.data.text
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, ''),
);
```
So probably a function could be created and used with a configuration option to ignore diacritics, thanks

**Comment by afonja14755** [comment]
Thank you for your request. I will look into this feature and try to add it.

**Comment by afonja14755** [comment]
Support added in [2.5.0](https://github.com/afonja14755/ux-select/releases/tag/v2.5.0) release
