### ISSUE TITLE
[Feature-Request] Display selected item on title box

### ISSUE THREAD

**Issue by William-H-M** [afonja14755/ux-select#7]
Hi, it'd be great to be able to config if on the title box to display either the **default** option of "Selected: x" or to display the text of the selected options, like the following:
![imagen](https://github.com/user-attachments/assets/7b127e30-9c4b-4d74-812a-939d5c20f6fa)

The way I did it for now is:

Add the optional parameter `displaySelectedItems` default false (a better name could be great) and the on `setSelectState` 
https://github.com/afonja14755/ux-select/blob/386732ac97cae87c1af7b008d3355aa1b0dd33d8/src/ux-select.ts#L168-L170

Replace with:
```
if (this.config.displaySelectedItems) {
  selectTitle.textContent = selectedTexts.join(', ');
} else {
  selectTitle.textContent = `${this.localization.selectedText} ${selectedTexts.length}`;
}
```
And to avoid the text overflow when there are too many selected items then on the styles we have this:
```
. ux-select__title {
    user-select: none;
    flex-grow: 1;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
```
Thanks

**Comment by afonja14755** [comment]
Thank you for your request. I will look into this feature and try to add it.

**Comment by afonja14755** [comment]
@William-H-M, feature added in last [release](https://github.com/afonja14755/ux-select/releases/tag/v2.6.0).

So you can use it by pass data attribute `data-is-display-selected-items="true"` or pass props in options object `isDisplaySelectedItems: true`.
